### ISSUE TITLE
Airflow Logo

### ISSUE THREAD

**Issue by PMAirflow** [AirFlow4Earth/AirFlow4Earth.github.io#7]
Hi guys,
I would suggest to take another logo as I think that this one does not really fit to the product / brand. I think the current one recalls a picture of a DNA or something similar.... :D maybe we should think about another logo here, I will do some research on that ....Lisa & Stefan

**Comment by qwertyone** [comment]
Look at the color transitions and the unclarity of the routes. Maybe it
needs made larger to clarify the concept.

**Comment by qwertyone** [comment]
Also, everything on the site is intended to be redone. If you create
something, I will gladly make changes. The nature of the project through
this web site service is intended by github to be a single page design.
Maybe there is something in the navigation that needs added or removed. I
will trust your judgment and revise accordingly.

**Comment by qwertyone** [comment]
This keeps inline with the initial idea. The DNA appearance is gone. https://github.com/AirFlow4Earth/AirFlow4Earth.github.io/blob/master/LogoAIRflow.gif?
