### ISSUE TITLE
GENERAL STYLE

### ISSUE THREAD

**Issue by PMAirflow** [AirFlow4Earth/AirFlow4Earth.github.io#8]
We think that the site should in general be a bit more modern and dynamic... I will try to find examples to post them here.... Lisa & Stefan

https://www.wizebit.com/ ....this for example ??

**Comment by qwertyone** [comment]
Keep in mind it should be just as simple as this. If a complicated example
is chosen, it will reallocate voluntary work time. All of the site is
intended to be temporary from its start.

**Comment by qwertyone** [comment]
It is fantastic to see that you have joined github. 🙂

**Comment by PMAirflow** [comment]
Anyways Aaron I think, that if the website looks unprofessional and is not appealing, people will not spend more than three seconds on it, that is the so to say trigger point for getting the people on the website. If they are not interested fron the beginning on, it does not make sense :)

**Comment by qwertyone** [comment]
I am seeking feedback to improve it. That does make sense and I understand
its importance.
